### ISSUE TITLE
OAuthException 191

### ISSUE THREAD

**Issue by spanish** [codesyntax/cs.auth.facebook#9]
Plone 4.3.10
cs.auth.facebook 1.1
collective.z3cform.norobots==1.4.2.2
collective.emailconfirmationregistration==1.2.0b5
Facebook API v2.12

I have created and configured the (web) app and activated and configured cs.auth.facebook, but always get this error if try login using Facebook:

{
   "error": {
      "message": "No se puede cargar la URL: El dominio de esta URL no está incluido en los dominios de la aplicación. Para poder cargar esta URL, añade todos los dominios y subdominios de tu aplicación al campo de dominios de la aplicación en la configuración de tu aplicación.",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "Hajfak5PTJn"
   }
}

Any idea?

Thanks

PS: I tried with https://www.google.com/search?q=OAuthException+191 tips, but no success.

**Comment by erral** [comment]
Facebook may have changed their API or app configuration *again* and now requires some extra parameter...

I can't look at it now, but will do during this week.

**Comment by erral** [comment]
I get the same error, I am unable to configure the Facebook app properly :cry: 

We don't have anymore this plugin in a production site, so I can't test it.

Please test this plugin (is newer) and check if it works with Facebook login: https://pypi.python.org/pypi/pas.plugins.authomatic

**Comment by sarn0ld** [comment]
My spanish is rusty, but when I get the error message right, you have to login to https://developers.facebook.com/apps/ and configure the URL from which the Facebook-Login is called. Example: https://www.your-website.com or http://localhost:8080/ when you are developing on your local machine...

![2019-10-09-110742](https://user-images.githubusercontent.com/44171387/66467909-871ebf80-ea85-11e9-9a3e-dd087d198724.png)

**Comment by sarn0ld** [comment]
We are using cs.auth.facebook in a production site and it is working fine.

**Comment by erral** [comment]
For the record: the translation from spanish is this:

"The URL can't be loaded. The domain of this URL is not included in the domains of the applications. To be able to load this URL, add all domain and subdomains of your application to the domains field in the application configuration screen."
